default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: satousan
  host: localhost

development:
  <<: *default
  database: arabiadaiki

test:
  <<: *default
  database: arabiadaiki

production:
  <<: *default
  database: arabiadaiki
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>